### ISSUE TITLE
Segfault (infinite recursion) in Frank

### ISSUE THREAD

**Issue by czechboy0** [nestproject/Frank#4]
Hey, I encountered (probably) a bug in Frank, where get(String, Closure) is calling itself and eventually crashing with a segfault. Here's my bare project which already shows it, just run `make run` to run the project and `make debug` to debug with lldb. https://github.com/czechboy0/ekg-swift

Please let me know if Frank is fine and I'm just doing something wrong, thanks!

**Comment by kylef** [comment]
This is completely a bug in Frank. I've fixed it and made a 0.2.3 release with the fix.

**Comment by czechboy0** [comment]
Awesome, thanks! :+1:
