### ISSUE TITLE
How would you daemonize?

### ISSUE THREAD

**Issue by subdigital** [nestproject/Frank#5]
I see that this uses Curassow by default. In a Curassow application you can pass `--daemonize` when running to have it run in the background.  Why I do this with a Frank application, it tells me the only options are `--timeout`, `--workers`, and `--bind`.

**Comment by kylef** [comment]
@subdigital there is no release of Curassow with the `--daemon` option, this was only introduced in master earlier today.

**Comment by subdigital** [comment]
Ah!  Funny that I saw that soon after it was committed. Thanks for the quick response.
